---
- name: ensure git
  package:
    name: git
    state: present

- name: ensure pihole group exists for pi user
  group:
    name: "{{ pihole_group }}"
    state: present

- name: create pihole user
  user:
    name: "{{ pihole_user }}"
    comment: pihole
    groups: "{{ pihole_group }}"

- name: Ensure pihole destination exists
  file:
    path: "{{ pihole_directory }}"
    state: directory
    mode: 0755
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"

- name: cloning pihole
  become: yes
  become_user: "{{ pihole_user }}"
  git:
    repo: "{{ pihole_repo }}"
    dest: "{{ pihole_directory }}"
    depth: "{{ pihole_repo_depth }}"
    version: "{{ pihole_branch }}"
    update: no

- name: Ensure that pihole configuration dir exists
  file:
    path: "{{ pihole_etc_dir }}"
    state: directory
    mode: 0755

- name: Push configuration file setupVars
  template:
    src: templates/setupVars.conf.j2
    dest: "{{ pihole_etc_dir }}/setupVars.conf"
    mode: 0644
  notify: reconfigure pi-hole dns

- name: check for existing installation of pihole
  stat:
    path: "{{ pihole_bin_path }}"
  register: pihole_bin
  changed_when: not pihole_bin.stat.exists

- name: installing pihole
  shell:
    chdir: "{{ pihole_directory }}/automated install/"
    cmd: "bash basic-install.sh --unattended"
  when:
    - not pihole_bin.stat.exists or pihole_reinstall

- name: Check for pihole updates
  command: "{{ pihole_bin_path }} updatePihole --check-only"
  register: updatecheck
  when:
    - pihole_bin.stat.exists
    - pihole_update|bool
    - not pihole_reinstall
  changed_when: updatecheck.stdout | regex_search('update available') != none
  notify: update pi-hole

- name: Enable/disable query log
  command: "{{ pihole_bin_path }} logging {% if pihole_setupvars_query_logging == true %}on{% else %}off{% endif %}"
  when: pihole_bin.stat.exists

- include_tasks: gravity.yml
  when: pihole_gravity_managed | bool

- include_tasks: domainlistings.yml

- name: Finished! ipv4
  debug:
    msg: "visit http://{{ pihole_setupvars_ipv4_address }}/admin/ to start managing your pi-hole"
  when:
    - pihole_setupvars_ipv4_address is defined
    - pihole_setupvars_ipv4_address|length > 0
    - pihole_setupvars_install_web_interface == "true"
    - pihole_setupvars_install_web_server == "true"

- name: Finished! ipv6
  debug:
    msg: "visit http://{{ pihole_setupvars_ipv6_address }}/admin/ to start managing your pi-hole"
  when:
    - pihole_setupvars_ipv6_address is defined
    - pihole_setupvars_ipv6_address|length > 0
    - pihole_setupvars_install_web_interface == "true"
    - pihole_setupvars_install_web_server == "true"
